= Workflow Needs (slightly pretentious: How I work)

:hp-tags: work

First post in a series of (we'll see)

== What I do

Broadly speaking I design projects, finding out what the objective is and massaging it to the point where it starts to be doable.

While all of this needs a generous amount of listening to people, a fair amount of specialised tools, a lot of patience and quite a bit of re-work, most of it has a lot to do with words and lists.

== Therefore, my text workflow needs

In the past, when I was workign for a consultancy, my main tool was a Molesike notebook, followed by some mindmaps and then specialised PM stuff.

A client engagement lasted on average about 6 months, while a notebook lasted about 3 months. No problem in carrying 2 notebooks. Done.

Now, and for the last 8 years, I work for a manufacturer of mbobile equipment, the projects last much longer than 6 months and the "client engagement" has been ongoing for more than seven years.

While I would still love to have every note in my notebook, it just does not work. Too much friction, too much searching.

Hence the search for a different methodology ...

Whatever I come up with, needs to be able to work with the following:

* Windows PC (my employer thinks, with due regard to some of the systems required, that this is non-negotiable)
* Android Phone (see above)
* Mac (at home)
* iPad Mini (everywhere)

